### ISSUE TITLE
Loading/token issues with multiple webmaps using federated services

### ISSUE THREAD

**Issue by woogers** [Esri/text-and-legend-map-storytelling-template-js#14]
I've been using the Text and Legend story map template in conjunction with a number of other templates, Esri-designed and otherwise. The issue I encounter seems to only happen with this template; it's the only template we have installed that can handle and display more than one webmap in the application.

Our setup uses multiple federated servers, hosting secured services, and a server with Portal stringing them all together. A user is able to create webmaps using the federated services and save them without issue. It's when that same user attempts to use more than one of those maps with this template that the problem occurs.

According to logs and network profiles, the template will call the API in order to check a user's credential/token to load the first webmap. Upon finding that the token is expired, invalid, or otherwise unusable, it will call the API to call the token service to generate a new token, which it then uses to load the rest of the webmaps, which all work and display as normal. But it doesn't attempt to reload the first webmap. The result is that all of the webmaps in the application will display except for the first one it tried to load.

**Comment by glazou** [comment]
Sorry about your issue. The text And Legend template has been in low maintenance for a while and we are going to deprecate it soon in favor of a new one named Story Map Series
 - https://github.com/Esri/map-series-storytelling-template-js/
 - http://storymaps.arcgis.com/en/app-list/map-series/

Sorry that I'm telling you to do more work but could you try to build your app with that new template and let us know it goes?

**Comment by woogers** [comment]
I will do that, and let you know what happens.

**Comment by woogers** [comment]
Is the Map Series template only compatible with Portal 10.3?

**Comment by glazou** [comment]
Yes Map Series has only been tested successfully on 10.3, see https://github.com/Esri/map-series-storytelling-template-js/#can-i-deploy-map-series-on-portal-for-arcgis

Map Series doesn't work on 10.2 because of incompatibility between the latest version of the API and Portal 10.2 (the app don't open at all). If you try to modify the version of the API that Map Series is using to be the same than your Portal, Map Series will generally work but some features will be broken. As far as I remember there is nothing major but we can't recommend that. If you go that way note that in 3.11, the path to access the JS API changed https://developers.arcgis.com/javascript/jshelp/new_v311.html

**Comment by woogers** [comment]
Alright, well, we plan on upgrading to 10.3 later in the year, so I guess I'll hold off on these newer templates until then. Thanks for your help!
